[project]
name = "pacmanai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BhagyeshKothalkar", email = "bhagyeshkothalkar@gmail.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "basedpyright>=1.39.10",
    "lightning>=2.6.5",
    "pandas>=3.0.5",
    "pygame>=2.6.1",
    "pytest>=9.1.1",
    "tensorboard>=2.21.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.28.0",
    "wandb>=0.28.2",
]

[project.scripts]
pacmanai = "pacmanai:main"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/xpu"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"


# [tool.basedpyright]
# executionEnvironments = [
#     { root = "." }
# ]

# TODO: change back to support strict
